test:
  stage: test
  only:
    - master
  script:
    -pip install -r requirements.txt
    -python manage.py test
deploy:
  stage: deploy
  variables:
    HEROKU_APP: django
  only:
    - master
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP --api-key=$HEROKU_TOKEN