# Generated by Django 3.2 on 2021-05-15 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigeon', '0010_channel_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='channel',
            field=models.ManyToManyField(to='pigeon.Channel'),
        ),
    ]
