# Generated by Django 3.2 on 2021-05-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pigeon', '0011_tag_channel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='channel',
            field=models.ManyToManyField(blank=True, null=True, to='pigeon.Channel'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='post',
            field=models.ManyToManyField(blank=True, null=True, to='pigeon.Post'),
        ),
    ]
