# Generated by Django 3.2 on 2021-05-21 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pigeon', '0013_auto_20210521_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pigeon.post'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='channel',
            field=models.ManyToManyField(blank=True, to='pigeon.Channel'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='post',
            field=models.ManyToManyField(blank=True, to='pigeon.Post'),
        ),
    ]
