# Generated by Django 3.2 on 2021-05-28 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pigeon', '0013_auto_20210527_2014'),
        ('pigeon', '0014_auto_20210521_1924'),
    ]

    operations = [
    ]
